version : "3.7"

services:  
  mpd:
    container_name: music-stream
    build:
      context: ./
    volumes:
      - ./ltts-data/playlists:/var/lib/mpd/playlists
      - ./ltts-data/music:/var/lib/mpd/music
    ports:
      - 6600:6600
      - 8080:8080
    restart: unless-stopped